[11.0][FIX] maintenance_equipment_purchase: cost
tegin/cb-maintenance pull request #42
Opened 2020-01-07 16:32 UTC by jarroyomorales

@etobella Cost es un Integer, quizas deberíamos hacerlo monetary....

2020-01-07 17:05 UTC, jarroyomorales commented
@etobella Lo del contact no me ha quedado del todo claro... lo he añadido en la vista simplified, aunque no he sido capaz de acceder a ella

2020-01-08 13:48 UTC, etobella requested changes

2020-01-08 13:48 UTC, etobella commented on cb_maintenance/models/maintenance_equipment.py
> +        if vals.get("code", "/") == "/":
Debe ser buscable por code, puedes revisarlo?

2020-01-08 14:56 UTC, jarroyomorales commented on cb_maintenance/models/maintenance_equipment.py
> +        if vals.get("code", "/") == "/":
Fixed

2020-01-08 14:59 UTC, jarroyomorales commented
@etobella  MUY IMPORTANTE: Desinstalar el módulo `maintenance_equipment_sequence` antes de hacer upgrade de este

2020-01-08 16:31 UTC, merged